enum LOGIN_TYPES {
  UPDATE_CREDENTIALS = '@login/UPDATE_CREDENTIALS',
  CHECK_CREDENTIALS = '@login/CHECK_CREDENTIALS',
  CREDENTIALS_FAIL = '@login/CREDENTIALS_FAIL',
  ISVALID_EMAIL = '@login/ISVALID_EMAIL',
  REQUEST_LOGIN = '@login/REQUEST_LOGIN',
  REQUEST_LOGIN_FAILURE = '@login/REQUEST_LOGIN_FAILURE',
}

export default LOGIN_TYPES;
